get http://localhost:8080/users/

###

get http://localhost:8080/users/1

###

get http://localhost:8080/Orders/1

###
get http://localhost:8080/Categories/

###
get http://localhost:8080/Products/3

###
get http://localhost:8080/Products/
 